client_id = "TU_ID_DE_CLIENTE"
name = "ImplementacionProducts-Afilink"
application_url = "https://afilink.com.uy/"
embedded = false

[access_scopes]
scopes = "read_products,read_inventory,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://afilink.com.uy/api/shopify/oauth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://afilink.com.uy/api/shopify/webhooks"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "orders/paid"]
uri = "https://afilink.com.uy/api/shopify/webhooks"
